# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 葫芦侠自动签到

on:
  schedule:
    # 设置启动时间，为 UTC 时间, UTC0点 对应北京时间8点
    - cron : '00 22 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
    - name: Start QD
      run: |
        python ./葫芦侠自动签到/main.py
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        USERID: ${{ secrets.USERID }}
        HLX_TID: ${{ secrets.HLX_TID }}
        HLX_USERID: ${{ secrets.HLX_USERID }}
        HLX_KEY: ${{ secrets.HLX_KEY }}
